import type { Metadata } from "next";
 import "../styles/globals.css";
import AuthProvider from "./context/AuthProvider";
 import { Toaster } from "react-hot-toast";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body>
      <AuthProvider>
        {children}
        <Toaster position="top-center" reverseOrder={false} />
         </AuthProvider>
      </body>
    </html>
  );
}
